
development:
  adapter: postgresql
  encoding: unicode
  database: mailing_app_development
  pool: 5
  
test:
  adapter: postgresql
  encoding: unicode
  database: mailing_app_test
  pool: 5
  
production:
  adapter: postgresql
  encoding: unicode
  database: mailing_app_production
  pool: 5
  